import React from 'react';
import './Services.css';
import Picture2 from './Picture2.png'
import Picture3 from './Picture3.png'
import Picture4 from './Picture4.png'
import Picture6 from './Picture6.png'
import { Link } from 'react-router-dom';
const Services = () => {
    return (
        <>

            <section className='container py-5 services'>
                <div className='row'>
                    <div className='col-12 col-lg-8'>
                        <div className='services-header'>
                            <h1>Our <h2>Services</h2></h1>
                            <div className="diamond-line-centered-theme-colored work-diamond"></div>
                            <p className=''>Learn about profitable financial opportunities with Yume One - Make Money Smarter with Our 4 User-Friendly Services: USD Generator, Coin Mining, and Fixed Deposit Package
                            </p>

                        </div>
                        <div className='row py-3'>
                            <div className='col-lg-6 col-md-6'>
                                <div className='row service-item'>
                                    <div className='col-4 p-0 text-end pe-3'>
                                        <Link to="/usd/generate">
                                            <img src={Picture2} className="card-img-top" alt="..." />
                                        </Link>
                                    </div>
                                    <div className='col-8'>
                                        <Link to="/usd/generate">
                                            <h3>Usd Generate</h3>
                                        </Link>
                                        <p>Dollars generated by the program.</p>
                                    </div>
                                </div>
                            </div>
                            <div className='col-lg-6 col-md-6'>
                                <div className='row service-item'>
                                    <div className='col-4 text-end pe-3'>
                                        <Link to="/coin/mining">
                                            <img src={Picture3} className="card-img-top" alt="..." />
                                        </Link>

                                    </div>
                                    <div className='col-8 mt-2'>
                                        <Link to="/coin/mining">
                                            <h3>Coin Mining</h3>
                                        </Link>
                                        <p>A mining operation for coins.</p>
                                    </div>
                                </div>
                            </div>

                            <div className='col-lg-6 col-md-6 '>
                                <div className='row service-item'>
                                    <div className='col-4 p-0 text-end pe-3'>
                                        <Link to="/fdp">
                                            <img src={Picture4} className="card-img-top" alt="..." />
                                        </Link>
                                    </div>

                                    <div className='col-8 mt-2'>
                                        <Link to="/fdp">

                                            <h3>Fixed Deposit Package</h3>
                                        </Link>
                                        <p>Plan for Fixed Deposits</p>
                                    </div>
                                </div>
                            </div>
                            <div className='col-lg-6 col-md-6'>
                                <div className='row service-item'>
                                    <div className='col-4 text-end pe-3'>
                                        <Link to="/entertainment">
                                            <img src={Picture6} className="card-img-top" alt="..." />
                                        </Link>

                                    </div>
                                    <div className='col-8 mt-2'>
                                        <Link to="/entertainment">
                                            <h3>Entertainment</h3>
                                        </Link>
                                        
                                        <p>Earn rewards as you play</p>
                                    </div>
                                </div>
                            </div>

                        </div>


                    </div>
                    <div className='col-lg-4'>
                        <div className='service-image'>
                            <img src="https://kodesolution.com/html/2018/cryptocoin-html/demo/images/services/1.png" alt="" />
                        </div>
                    </div>
                </div>
            </section>

        </>
    );
};

export default Services;